# AREWA DATA SCIENCE ACADEMY

***Deep Learning Cohort 2.0***

**Name:** Amalai Rham Machunga

**Email:** amachunga@gmail.com

**Title:** Week 1 Solution



# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [107]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [108]:
# Import torch
import torch


# Create random tensor
rand_tensor_x = torch.rand(7, 7)
print("RANDOM TENSOR:\n", rand_tensor_x, rand_tensor_x.size())


RANDOM TENSOR:
 tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
        [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
        [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
        [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
        [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
        [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]]) torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [109]:
# Create another random tensor
rand_tensor_y = torch.rand(1, 7)

# Transpose y
tansposed_tensor_y = rand_tensor_y.t()

# Perform matrix multiplication
multi_z = torch.matmul(rand_tensor_x, tansposed_tensor_y)
print(multi_z, multi_z.size())


tensor([[1.6914],
        [1.7581],
        [2.0906],
        [1.8975],
        [1.7585],
        [1.7961],
        [1.8900]]) torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [110]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
rand_tensor_a = torch.rand(7, 7)
print("TENSOR a:\n", rand_tensor_a, rand_tensor_a.size())

print("-----------------------------------------------------------------------")

rand_tensor_b = torch.rand(1, 7)
print("TENSOR b:\n", rand_tensor_b, rand_tensor_b.size())

# Transpose tensor b
transposed_tensor_b = rand_tensor_b.t()

print("-----------------------------------------------------------------------")

# Matrix multiply tensors
Multi_c = torch.matmul(rand_tensor_a, transposed_tensor_b)
print("Multiplication Result:\n", Multi_c, Multi_c.size())

TENSOR a:
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]) torch.Size([7, 7])
-----------------------------------------------------------------------
TENSOR b:
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]) torch.Size([1, 7])
-----------------------------------------------------------------------
Multiplication Result:
 tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [111]:
# Set random seed on the GPU
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(1234)
    print("GPU is available")
else:
    print("NO GPU available")



GPU is available



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [112]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    print("GPU available")
else:
    print("GPU not available")

print("-----------------------------------------------------------------------")

# Create two random tensors on GPU

rand_tensor_A = torch.rand(2, 3).cuda()
print("Tensor A:\n", rand_tensor_A, rand_tensor_A.size())

print("-----------------------------------------------------------------------")

rand_tensor_B = torch.rand(2, 3).cuda()
print("Tensor B:\n", rand_tensor_B, rand_tensor_B.size())

GPU available
-----------------------------------------------------------------------
Tensor A:
 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') torch.Size([2, 3])
-----------------------------------------------------------------------
Tensor B:
 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0') torch.Size([2, 3])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [113]:
# Perform matmul on tensor_A and tensor_B

Tranposed_tensor_B = rand_tensor_B.t()
print("TRANSPOSED MATRIX:\n", Tranposed_tensor_B, Tranposed_tensor_B.size())

print("-----------------------------------------------------------------------")

multi_result = torch.matmul(rand_tensor_A, Tranposed_tensor_B)
print("MULTIPLICATION RESULT\n", multi_result, multi_result.size())




TRANSPOSED MATRIX:
 tensor([[0.0518, 0.3315],
        [0.4681, 0.7837],
        [0.6738, 0.5631]], device='cuda:0') torch.Size([3, 2])
-----------------------------------------------------------------------
MULTIPLICATION RESULT
 tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [114]:
# Find max
max_value = torch.max(multi_result)
print("MAX VALUE:\n", max_value)

print("-----------------------------------------------------------------------")

# Find min
min_value = torch.min(multi_result)
print("MIN VALUE:\n", min_value)


MAX VALUE:
 tensor(0.5617, device='cuda:0')
-----------------------------------------------------------------------
MIN VALUE:
 tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [115]:
# Find arg max
max_index = torch.argmax(multi_result)
print("MAX INDEX: \n", max_index)

print("-----------------------------------------------------------------------")

# Find arg min
min_index = torch.argmin(multi_result)
print("MIN INDEX: \n", min_index)


MAX INDEX: 
 tensor(3, device='cuda:0')
-----------------------------------------------------------------------
MIN INDEX: 
 tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [116]:
# Set seed
torch.manual_seed(7)


# Create random tensor
rand_tensor_x = torch.rand(1, 1, 1, 10)
print("RANDOM TENSOR:\n", rand_tensor_x, rand_tensor_x.size())


# Remove single dimensions
squeezed_tensor = torch.squeeze(rand_tensor_x)
print("SQUEEZED TENSOR:\n", squeezed_tensor, squeezed_tensor.size())


# Print out tensors and their shapes
print("-----------------------------------------------------------------------")
print("RANDOM TENSOR:\n", rand_tensor_x, rand_tensor_x.size())
print("SQUEEZED TENSOR:\n", squeezed_tensor, squeezed_tensor.size())



RANDOM TENSOR:
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
SQUEEZED TENSOR:
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
-----------------------------------------------------------------------
RANDOM TENSOR:
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
SQUEEZED TENSOR:
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
